//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVideo.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Video
    {
        public int ID { get; set; }
        public string videoName { get; set; }
        public Nullable<int> videoKind { get; set; }
        public string describe { get; set; }
        public string poster { get; set; }
        public string videoPath { get; set; }

        public virtual VideoKind VideoKind1 { get; set; }

        public override string ToString()
        {
            return string.Format("{0}", videoName);
        }
    }
}
